#!/bin/bash
# -*- mode: sh -*-
# create -v4 logs for DWGs, you can override -v?
srcdir="."
top_builddir="."

make -s -j4 -C src || exit 1
make -s -j4 -C programs dwgread || exit 1
# programs/dwgread
v=-v4
# dummy to please shellcheck
test -z "$v" && echo $top_builddir
ob="$b"
log=

for d in "$@"; do
    # we do use bash
    case $d in
        -v*)
             v="$d"
             ;;
        -l*)
             log="$(cut "$d" -c2-)"
             ;;
        *)
        if [ ! -f "$d" ]; then
            if [ -f "$srcdir/test/test-data/$d" ]; then
                d="$srcdir/test/test-data/$d"
            else
                if [ -f "$srcdir/test/test-data/$d.dwg" ]; then
                    d="$srcdir/test/test-data/$d.dwg"
                fi
            fi
        fi
        xd=$(dirname "$d")
        dir=_$(basename "$xd")
        if [ -z "$log" ]; then
            case "$d" in
                *to/*)
                    x1=$(dirname "$xd")
                    dir=_$(basename "$xd")_$(basename "$x1")
                    ;;
                *test-old/*)
                    x1=$(dirname "$xd")
                    dir=_$(basename "$xd")_$(basename "$x1")
                    ;;
            esac
        fi
        if [ "$dir" = "_test-data" ]; then dir=""; fi
        if [ "$dir" = "_td" ]; then dir=""; fi
        if [ "$dir" = "_." ]; then dir=""; fi
        b=$(basename "$d" .dwg)
        b=$(basename "$b" .DWG)
        [ -z "$log" ] && log="$b$dir.log"
        echo "timeout 10  programs/dwgread $v $d 2>$log"
        # (sleep 12s; killall dwgread 2>/dev/null) &
        timeout 10  programs/dwgread "$v" "$d" 2>"$log"
        tail -n2 "$log"
        log=
        ;;
    esac
done
v=
b="$ob"
