# CMake generated Testfile for 
# Source directory: /home/raptor/nanomq-0.17.5/nng/tests
# Build directory: /home/raptor/nanomq-0.17.5/nng/tests
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(nng.device "/home/raptor/nanomq-0.17.5/nng/tests/device" "-v" "-p" "TEST_PORT=13000")
set_tests_properties(nng.device PROPERTIES  TIMEOUT "5" _BACKTRACE_TRIPLES "/home/raptor/nanomq-0.17.5/nng/tests/CMakeLists.txt;57;add_test;/home/raptor/nanomq-0.17.5/nng/tests/CMakeLists.txt;127;add_nng_test;/home/raptor/nanomq-0.17.5/nng/tests/CMakeLists.txt;0;")
add_test(nng.files "/home/raptor/nanomq-0.17.5/nng/tests/files" "-v" "-p" "TEST_PORT=13020")
set_tests_properties(nng.files PROPERTIES  TIMEOUT "5" _BACKTRACE_TRIPLES "/home/raptor/nanomq-0.17.5/nng/tests/CMakeLists.txt;57;add_test;/home/raptor/nanomq-0.17.5/nng/tests/CMakeLists.txt;128;add_nng_test;/home/raptor/nanomq-0.17.5/nng/tests/CMakeLists.txt;0;")
add_test(nng.httpclient "/home/raptor/nanomq-0.17.5/nng/tests/httpclient" "-v" "-p" "TEST_PORT=13040")
set_tests_properties(nng.httpclient PROPERTIES  TIMEOUT "60" _BACKTRACE_TRIPLES "/home/raptor/nanomq-0.17.5/nng/tests/CMakeLists.txt;57;add_test;/home/raptor/nanomq-0.17.5/nng/tests/CMakeLists.txt;90;add_nng_test;/home/raptor/nanomq-0.17.5/nng/tests/CMakeLists.txt;129;add_nng_test1;/home/raptor/nanomq-0.17.5/nng/tests/CMakeLists.txt;0;")
add_test(nng.httpserver "/home/raptor/nanomq-0.17.5/nng/tests/httpserver" "-v" "-p" "TEST_PORT=13060")
set_tests_properties(nng.httpserver PROPERTIES  TIMEOUT "30" _BACKTRACE_TRIPLES "/home/raptor/nanomq-0.17.5/nng/tests/CMakeLists.txt;57;add_test;/home/raptor/nanomq-0.17.5/nng/tests/CMakeLists.txt;90;add_nng_test;/home/raptor/nanomq-0.17.5/nng/tests/CMakeLists.txt;130;add_nng_test1;/home/raptor/nanomq-0.17.5/nng/tests/CMakeLists.txt;0;")
add_test(nng.inproc "/home/raptor/nanomq-0.17.5/nng/tests/inproc" "-v" "-p" "TEST_PORT=13080")
set_tests_properties(nng.inproc PROPERTIES  TIMEOUT "5" _BACKTRACE_TRIPLES "/home/raptor/nanomq-0.17.5/nng/tests/CMakeLists.txt;57;add_test;/home/raptor/nanomq-0.17.5/nng/tests/CMakeLists.txt;131;add_nng_test;/home/raptor/nanomq-0.17.5/nng/tests/CMakeLists.txt;0;")
add_test(nng.ipc "/home/raptor/nanomq-0.17.5/nng/tests/ipc" "-v" "-p" "TEST_PORT=13100")
set_tests_properties(nng.ipc PROPERTIES  TIMEOUT "5" _BACKTRACE_TRIPLES "/home/raptor/nanomq-0.17.5/nng/tests/CMakeLists.txt;57;add_test;/home/raptor/nanomq-0.17.5/nng/tests/CMakeLists.txt;132;add_nng_test;/home/raptor/nanomq-0.17.5/nng/tests/CMakeLists.txt;0;")
add_test(nng.ipcsupp "/home/raptor/nanomq-0.17.5/nng/tests/ipcsupp" "-v" "-p" "TEST_PORT=13120")
set_tests_properties(nng.ipcsupp PROPERTIES  TIMEOUT "10" _BACKTRACE_TRIPLES "/home/raptor/nanomq-0.17.5/nng/tests/CMakeLists.txt;57;add_test;/home/raptor/nanomq-0.17.5/nng/tests/CMakeLists.txt;133;add_nng_test;/home/raptor/nanomq-0.17.5/nng/tests/CMakeLists.txt;0;")
add_test(nng.multistress "/home/raptor/nanomq-0.17.5/nng/tests/multistress" "-v" "-p" "TEST_PORT=13140")
set_tests_properties(nng.multistress PROPERTIES  TIMEOUT "60" _BACKTRACE_TRIPLES "/home/raptor/nanomq-0.17.5/nng/tests/CMakeLists.txt;57;add_test;/home/raptor/nanomq-0.17.5/nng/tests/CMakeLists.txt;134;add_nng_test;/home/raptor/nanomq-0.17.5/nng/tests/CMakeLists.txt;0;")
add_test(nng.nonblock "/home/raptor/nanomq-0.17.5/nng/tests/nonblock" "-v" "-p" "TEST_PORT=13160")
set_tests_properties(nng.nonblock PROPERTIES  TIMEOUT "60" _BACKTRACE_TRIPLES "/home/raptor/nanomq-0.17.5/nng/tests/CMakeLists.txt;57;add_test;/home/raptor/nanomq-0.17.5/nng/tests/CMakeLists.txt;135;add_nng_test;/home/raptor/nanomq-0.17.5/nng/tests/CMakeLists.txt;0;")
add_test(nng.options "/home/raptor/nanomq-0.17.5/nng/tests/options" "-v" "-p" "TEST_PORT=13180")
set_tests_properties(nng.options PROPERTIES  TIMEOUT "5" _BACKTRACE_TRIPLES "/home/raptor/nanomq-0.17.5/nng/tests/CMakeLists.txt;57;add_test;/home/raptor/nanomq-0.17.5/nng/tests/CMakeLists.txt;136;add_nng_test;/home/raptor/nanomq-0.17.5/nng/tests/CMakeLists.txt;0;")
add_test(nng.pipe "/home/raptor/nanomq-0.17.5/nng/tests/pipe" "-v" "-p" "TEST_PORT=13200")
set_tests_properties(nng.pipe PROPERTIES  TIMEOUT "5" _BACKTRACE_TRIPLES "/home/raptor/nanomq-0.17.5/nng/tests/CMakeLists.txt;57;add_test;/home/raptor/nanomq-0.17.5/nng/tests/CMakeLists.txt;137;add_nng_test;/home/raptor/nanomq-0.17.5/nng/tests/CMakeLists.txt;0;")
add_test(nng.pollfd "/home/raptor/nanomq-0.17.5/nng/tests/pollfd" "-v" "-p" "TEST_PORT=13220")
set_tests_properties(nng.pollfd PROPERTIES  TIMEOUT "5" _BACKTRACE_TRIPLES "/home/raptor/nanomq-0.17.5/nng/tests/CMakeLists.txt;57;add_test;/home/raptor/nanomq-0.17.5/nng/tests/CMakeLists.txt;138;add_nng_test;/home/raptor/nanomq-0.17.5/nng/tests/CMakeLists.txt;0;")
add_test(nng.scalability "/home/raptor/nanomq-0.17.5/nng/tests/scalability" "-v" "-p" "TEST_PORT=13240")
set_tests_properties(nng.scalability PROPERTIES  TIMEOUT "20" _BACKTRACE_TRIPLES "/home/raptor/nanomq-0.17.5/nng/tests/CMakeLists.txt;57;add_test;/home/raptor/nanomq-0.17.5/nng/tests/CMakeLists.txt;139;add_nng_test;/home/raptor/nanomq-0.17.5/nng/tests/CMakeLists.txt;0;")
add_test(nng.synch "/home/raptor/nanomq-0.17.5/nng/tests/synch" "-v" "-p" "TEST_PORT=13260")
set_tests_properties(nng.synch PROPERTIES  TIMEOUT "5" _BACKTRACE_TRIPLES "/home/raptor/nanomq-0.17.5/nng/tests/CMakeLists.txt;57;add_test;/home/raptor/nanomq-0.17.5/nng/tests/CMakeLists.txt;140;add_nng_test;/home/raptor/nanomq-0.17.5/nng/tests/CMakeLists.txt;0;")
add_test(nng.tls "/home/raptor/nanomq-0.17.5/nng/tests/tls" "-v" "-p" "TEST_PORT=13280")
set_tests_properties(nng.tls PROPERTIES  TIMEOUT "60" _BACKTRACE_TRIPLES "/home/raptor/nanomq-0.17.5/nng/tests/CMakeLists.txt;57;add_test;/home/raptor/nanomq-0.17.5/nng/tests/CMakeLists.txt;141;add_nng_test;/home/raptor/nanomq-0.17.5/nng/tests/CMakeLists.txt;0;")
add_test(nng.tcpsupp "/home/raptor/nanomq-0.17.5/nng/tests/tcpsupp" "-v" "-p" "TEST_PORT=13300")
set_tests_properties(nng.tcpsupp PROPERTIES  TIMEOUT "10" _BACKTRACE_TRIPLES "/home/raptor/nanomq-0.17.5/nng/tests/CMakeLists.txt;57;add_test;/home/raptor/nanomq-0.17.5/nng/tests/CMakeLists.txt;142;add_nng_test;/home/raptor/nanomq-0.17.5/nng/tests/CMakeLists.txt;0;")
add_test(nng.tcp "/home/raptor/nanomq-0.17.5/nng/tests/tcp" "-v" "-p" "TEST_PORT=13320")
set_tests_properties(nng.tcp PROPERTIES  TIMEOUT "180" _BACKTRACE_TRIPLES "/home/raptor/nanomq-0.17.5/nng/tests/CMakeLists.txt;57;add_test;/home/raptor/nanomq-0.17.5/nng/tests/CMakeLists.txt;143;add_nng_test;/home/raptor/nanomq-0.17.5/nng/tests/CMakeLists.txt;0;")
add_test(nng.mqtt_tcp "/home/raptor/nanomq-0.17.5/nng/tests/mqtt_tcp" "-v" "-p" "TEST_PORT=13340")
set_tests_properties(nng.mqtt_tcp PROPERTIES  TIMEOUT "180" _BACKTRACE_TRIPLES "/home/raptor/nanomq-0.17.5/nng/tests/CMakeLists.txt;57;add_test;/home/raptor/nanomq-0.17.5/nng/tests/CMakeLists.txt;144;add_nng_test;/home/raptor/nanomq-0.17.5/nng/tests/CMakeLists.txt;0;")
add_test(nng.tcp6 "/home/raptor/nanomq-0.17.5/nng/tests/tcp6" "-v" "-p" "TEST_PORT=13360")
set_tests_properties(nng.tcp6 PROPERTIES  TIMEOUT "60" _BACKTRACE_TRIPLES "/home/raptor/nanomq-0.17.5/nng/tests/CMakeLists.txt;57;add_test;/home/raptor/nanomq-0.17.5/nng/tests/CMakeLists.txt;145;add_nng_test;/home/raptor/nanomq-0.17.5/nng/tests/CMakeLists.txt;0;")
add_test(nng.udp "/home/raptor/nanomq-0.17.5/nng/tests/udp" "-v" "-p" "TEST_PORT=13380")
set_tests_properties(nng.udp PROPERTIES  TIMEOUT "5" _BACKTRACE_TRIPLES "/home/raptor/nanomq-0.17.5/nng/tests/CMakeLists.txt;57;add_test;/home/raptor/nanomq-0.17.5/nng/tests/CMakeLists.txt;146;add_nng_test;/home/raptor/nanomq-0.17.5/nng/tests/CMakeLists.txt;0;")
add_test(nng.ws "/home/raptor/nanomq-0.17.5/nng/tests/ws" "-v" "-p" "TEST_PORT=13400")
set_tests_properties(nng.ws PROPERTIES  TIMEOUT "30" _BACKTRACE_TRIPLES "/home/raptor/nanomq-0.17.5/nng/tests/CMakeLists.txt;57;add_test;/home/raptor/nanomq-0.17.5/nng/tests/CMakeLists.txt;147;add_nng_test;/home/raptor/nanomq-0.17.5/nng/tests/CMakeLists.txt;0;")
add_test(nng.wss "/home/raptor/nanomq-0.17.5/nng/tests/wss" "-v" "-p" "TEST_PORT=13420")
set_tests_properties(nng.wss PROPERTIES  TIMEOUT "30" _BACKTRACE_TRIPLES "/home/raptor/nanomq-0.17.5/nng/tests/CMakeLists.txt;57;add_test;/home/raptor/nanomq-0.17.5/nng/tests/CMakeLists.txt;148;add_nng_test;/home/raptor/nanomq-0.17.5/nng/tests/CMakeLists.txt;0;")
add_test(nng.reqctx "/home/raptor/nanomq-0.17.5/nng/tests/reqctx" "-v" "-p" "TEST_PORT=13440")
set_tests_properties(nng.reqctx PROPERTIES  TIMEOUT "5" _BACKTRACE_TRIPLES "/home/raptor/nanomq-0.17.5/nng/tests/CMakeLists.txt;57;add_test;/home/raptor/nanomq-0.17.5/nng/tests/CMakeLists.txt;151;add_nng_test;/home/raptor/nanomq-0.17.5/nng/tests/CMakeLists.txt;0;")
add_test(nng.reqstress "/home/raptor/nanomq-0.17.5/nng/tests/reqstress" "-v" "-p" "TEST_PORT=13460")
set_tests_properties(nng.reqstress PROPERTIES  TIMEOUT "60" _BACKTRACE_TRIPLES "/home/raptor/nanomq-0.17.5/nng/tests/CMakeLists.txt;57;add_test;/home/raptor/nanomq-0.17.5/nng/tests/CMakeLists.txt;152;add_nng_test;/home/raptor/nanomq-0.17.5/nng/tests/CMakeLists.txt;0;")
add_test(nng.compat_block "/home/raptor/nanomq-0.17.5/nng/tests/compat_block" "13480")
set_tests_properties(nng.compat_block PROPERTIES  TIMEOUT "10" _BACKTRACE_TRIPLES "/home/raptor/nanomq-0.17.5/nng/tests/CMakeLists.txt;72;add_test;/home/raptor/nanomq-0.17.5/nng/tests/CMakeLists.txt;159;add_nng_compat_test;/home/raptor/nanomq-0.17.5/nng/tests/CMakeLists.txt;0;")
add_test(nng.compat_bug777 "/home/raptor/nanomq-0.17.5/nng/tests/compat_bug777" "13500")
set_tests_properties(nng.compat_bug777 PROPERTIES  TIMEOUT "10" _BACKTRACE_TRIPLES "/home/raptor/nanomq-0.17.5/nng/tests/CMakeLists.txt;72;add_test;/home/raptor/nanomq-0.17.5/nng/tests/CMakeLists.txt;160;add_nng_compat_test;/home/raptor/nanomq-0.17.5/nng/tests/CMakeLists.txt;0;")
add_test(nng.compat_bus "/home/raptor/nanomq-0.17.5/nng/tests/compat_bus" "13520")
set_tests_properties(nng.compat_bus PROPERTIES  TIMEOUT "10" _BACKTRACE_TRIPLES "/home/raptor/nanomq-0.17.5/nng/tests/CMakeLists.txt;72;add_test;/home/raptor/nanomq-0.17.5/nng/tests/CMakeLists.txt;161;add_nng_compat_test;/home/raptor/nanomq-0.17.5/nng/tests/CMakeLists.txt;0;")
add_test(nng.compat_cmsg "/home/raptor/nanomq-0.17.5/nng/tests/compat_cmsg" "13540")
set_tests_properties(nng.compat_cmsg PROPERTIES  TIMEOUT "10" _BACKTRACE_TRIPLES "/home/raptor/nanomq-0.17.5/nng/tests/CMakeLists.txt;72;add_test;/home/raptor/nanomq-0.17.5/nng/tests/CMakeLists.txt;162;add_nng_compat_test;/home/raptor/nanomq-0.17.5/nng/tests/CMakeLists.txt;0;")
add_test(nng.compat_msg "/home/raptor/nanomq-0.17.5/nng/tests/compat_msg" "13560")
set_tests_properties(nng.compat_msg PROPERTIES  TIMEOUT "10" _BACKTRACE_TRIPLES "/home/raptor/nanomq-0.17.5/nng/tests/CMakeLists.txt;72;add_test;/home/raptor/nanomq-0.17.5/nng/tests/CMakeLists.txt;163;add_nng_compat_test;/home/raptor/nanomq-0.17.5/nng/tests/CMakeLists.txt;0;")
add_test(nng.compat_iovec "/home/raptor/nanomq-0.17.5/nng/tests/compat_iovec" "13580")
set_tests_properties(nng.compat_iovec PROPERTIES  TIMEOUT "10" _BACKTRACE_TRIPLES "/home/raptor/nanomq-0.17.5/nng/tests/CMakeLists.txt;72;add_test;/home/raptor/nanomq-0.17.5/nng/tests/CMakeLists.txt;164;add_nng_compat_test;/home/raptor/nanomq-0.17.5/nng/tests/CMakeLists.txt;0;")
add_test(nng.compat_device "/home/raptor/nanomq-0.17.5/nng/tests/compat_device" "13600")
set_tests_properties(nng.compat_device PROPERTIES  TIMEOUT "10" _BACKTRACE_TRIPLES "/home/raptor/nanomq-0.17.5/nng/tests/CMakeLists.txt;72;add_test;/home/raptor/nanomq-0.17.5/nng/tests/CMakeLists.txt;165;add_nng_compat_test;/home/raptor/nanomq-0.17.5/nng/tests/CMakeLists.txt;0;")
add_test(nng.compat_pair "/home/raptor/nanomq-0.17.5/nng/tests/compat_pair" "13620")
set_tests_properties(nng.compat_pair PROPERTIES  TIMEOUT "10" _BACKTRACE_TRIPLES "/home/raptor/nanomq-0.17.5/nng/tests/CMakeLists.txt;72;add_test;/home/raptor/nanomq-0.17.5/nng/tests/CMakeLists.txt;166;add_nng_compat_test;/home/raptor/nanomq-0.17.5/nng/tests/CMakeLists.txt;0;")
add_test(nng.compat_pipeline "/home/raptor/nanomq-0.17.5/nng/tests/compat_pipeline" "13640")
set_tests_properties(nng.compat_pipeline PROPERTIES  TIMEOUT "10" _BACKTRACE_TRIPLES "/home/raptor/nanomq-0.17.5/nng/tests/CMakeLists.txt;72;add_test;/home/raptor/nanomq-0.17.5/nng/tests/CMakeLists.txt;167;add_nng_compat_test;/home/raptor/nanomq-0.17.5/nng/tests/CMakeLists.txt;0;")
add_test(nng.compat_poll "/home/raptor/nanomq-0.17.5/nng/tests/compat_poll" "13660")
set_tests_properties(nng.compat_poll PROPERTIES  TIMEOUT "10" _BACKTRACE_TRIPLES "/home/raptor/nanomq-0.17.5/nng/tests/CMakeLists.txt;72;add_test;/home/raptor/nanomq-0.17.5/nng/tests/CMakeLists.txt;168;add_nng_compat_test;/home/raptor/nanomq-0.17.5/nng/tests/CMakeLists.txt;0;")
add_test(nng.compat_reqrep "/home/raptor/nanomq-0.17.5/nng/tests/compat_reqrep" "13680")
set_tests_properties(nng.compat_reqrep PROPERTIES  TIMEOUT "10" _BACKTRACE_TRIPLES "/home/raptor/nanomq-0.17.5/nng/tests/CMakeLists.txt;72;add_test;/home/raptor/nanomq-0.17.5/nng/tests/CMakeLists.txt;169;add_nng_compat_test;/home/raptor/nanomq-0.17.5/nng/tests/CMakeLists.txt;0;")
add_test(nng.compat_survey "/home/raptor/nanomq-0.17.5/nng/tests/compat_survey" "13700")
set_tests_properties(nng.compat_survey PROPERTIES  TIMEOUT "10" _BACKTRACE_TRIPLES "/home/raptor/nanomq-0.17.5/nng/tests/CMakeLists.txt;72;add_test;/home/raptor/nanomq-0.17.5/nng/tests/CMakeLists.txt;170;add_nng_compat_test;/home/raptor/nanomq-0.17.5/nng/tests/CMakeLists.txt;0;")
add_test(nng.compat_reqttl "/home/raptor/nanomq-0.17.5/nng/tests/compat_reqttl" "13720")
set_tests_properties(nng.compat_reqttl PROPERTIES  TIMEOUT "10" _BACKTRACE_TRIPLES "/home/raptor/nanomq-0.17.5/nng/tests/CMakeLists.txt;72;add_test;/home/raptor/nanomq-0.17.5/nng/tests/CMakeLists.txt;171;add_nng_compat_test;/home/raptor/nanomq-0.17.5/nng/tests/CMakeLists.txt;0;")
add_test(nng.compat_shutdown "/home/raptor/nanomq-0.17.5/nng/tests/compat_shutdown" "13740")
set_tests_properties(nng.compat_shutdown PROPERTIES  TIMEOUT "10" _BACKTRACE_TRIPLES "/home/raptor/nanomq-0.17.5/nng/tests/CMakeLists.txt;72;add_test;/home/raptor/nanomq-0.17.5/nng/tests/CMakeLists.txt;172;add_nng_compat_test;/home/raptor/nanomq-0.17.5/nng/tests/CMakeLists.txt;0;")
add_test(nng.compat_surveyttl "/home/raptor/nanomq-0.17.5/nng/tests/compat_surveyttl" "13760")
set_tests_properties(nng.compat_surveyttl PROPERTIES  TIMEOUT "10" _BACKTRACE_TRIPLES "/home/raptor/nanomq-0.17.5/nng/tests/CMakeLists.txt;72;add_test;/home/raptor/nanomq-0.17.5/nng/tests/CMakeLists.txt;173;add_nng_compat_test;/home/raptor/nanomq-0.17.5/nng/tests/CMakeLists.txt;0;")
add_test(nng.compat_options "/home/raptor/nanomq-0.17.5/nng/tests/compat_options" "-v" "-p" "TEST_PORT=13780")
set_tests_properties(nng.compat_options PROPERTIES  TIMEOUT "5" _BACKTRACE_TRIPLES "/home/raptor/nanomq-0.17.5/nng/tests/CMakeLists.txt;57;add_test;/home/raptor/nanomq-0.17.5/nng/tests/CMakeLists.txt;177;add_nng_test;/home/raptor/nanomq-0.17.5/nng/tests/CMakeLists.txt;0;")
add_test(nng.cplusplus_pair "/home/raptor/nanomq-0.17.5/nng/tests/cplusplus_pair")
set_tests_properties(nng.cplusplus_pair PROPERTIES  TIMEOUT "5" _BACKTRACE_TRIPLES "/home/raptor/nanomq-0.17.5/nng/tests/CMakeLists.txt;82;add_test;/home/raptor/nanomq-0.17.5/nng/tests/CMakeLists.txt;180;add_nng_cpp_test;/home/raptor/nanomq-0.17.5/nng/tests/CMakeLists.txt;0;")
