#define FUNCNAME_quitfm 0
#define FUNCNAME_accessKey 1
#define FUNCNAME_adBmark 2
#define FUNCNAME_setAlarm 3
#define FUNCNAME_backBf 4
#define FUNCNAME_goLineF 5
#define FUNCNAME_ldBmark 6
#define FUNCNAME_ctrCsrH 7
#define FUNCNAME_ctrCsrV 8
#define FUNCNAME_docCSet 9
#define FUNCNAME_closeT 10
#define FUNCNAME_closeTMs 11
#define FUNCNAME_execCmd 12
#define FUNCNAME_cooLst 13
#define FUNCNAME_cursorBottom 14
#define FUNCNAME_cursorMiddle 15
#define FUNCNAME_cursorTop 16
#define FUNCNAME_defCSet 17
#define FUNCNAME_defKey 18
#define FUNCNAME_deletePrevBuf 19
#define FUNCNAME_dictwordat 20
#define FUNCNAME_dictword 21
#define FUNCNAME_dispI 22
#define FUNCNAME_ldown1 23
#define FUNCNAME_ldDL 24
#define FUNCNAME_svSrc 25
#define FUNCNAME_editBf 26
#define FUNCNAME_editScr 27
#define FUNCNAME_goLineL 28
#define FUNCNAME_escbmap 29
#define FUNCNAME_escmap 30
#define FUNCNAME_execsh 31
#define FUNCNAME_extbrz 33
#define FUNCNAME_linkbrz 34
#define FUNCNAME_rFrame 35
#define FUNCNAME_goURL 36
#define FUNCNAME_goHome 37
#define FUNCNAME_goLine 38
#define FUNCNAME_followA 39
#define FUNCNAME_gorURL 40
#define FUNCNAME_ldhelp 41
#define FUNCNAME_ldHist 42
#define FUNCNAME_pginfo 43
#define FUNCNAME_susp 44
#define FUNCNAME_isrchbak 45
#define FUNCNAME_isrchfor 46
#define FUNCNAME_col1L 47
#define FUNCNAME_linbeg 48
#define FUNCNAME_linend 49
#define FUNCNAME_curlno 50
#define FUNCNAME_topA 51
#define FUNCNAME_lastA 52
#define FUNCNAME_linkMn 53
#define FUNCNAME_nthA 54
#define FUNCNAME_linkLst 55
#define FUNCNAME_listMn 56
#define FUNCNAME_ldfile 57
#define FUNCNAME_mainMn 58
#define FUNCNAME__mark 59
#define FUNCNAME_chkNMID 60
#define FUNCNAME_chkURL 61
#define FUNCNAME_chkWORD 62
#define FUNCNAME_menuMs 64
#define FUNCNAME_mouse 65
#define FUNCNAME_msToggle 66
#define FUNCNAME_movD1 67
#define FUNCNAME_movD 68
#define FUNCNAME_movL1 69
#define FUNCNAME_movL 70
#define FUNCNAME_movlistMn 71
#define FUNCNAME_movMs 72
#define FUNCNAME_movR1 73
#define FUNCNAME_movR 74
#define FUNCNAME_movU1 75
#define FUNCNAME_movU 76
#define FUNCNAME_msgs 77
#define FUNCNAME_multimap 78
#define FUNCNAME_newT 79
#define FUNCNAME_nextD 80
#define FUNCNAME_hpgFore 81
#define FUNCNAME_nextL 82
#define FUNCNAME_nextLU 83
#define FUNCNAME_nextA 84
#define FUNCNAME_nextMk 85
#define FUNCNAME_nextBf 86
#define FUNCNAME_pgFore 87
#define FUNCNAME_nextRD 88
#define FUNCNAME_nextR 89
#define FUNCNAME_nextT 90
#define FUNCNAME_nextU 91
#define FUNCNAME_nextVA 92
#define FUNCNAME_movRW 93
#define FUNCNAME_nulcmd 94
#define FUNCNAME_ldOpt 97
#define FUNCNAME_pcmap 98
#define FUNCNAME_curURL 99
#define FUNCNAME_peekIMG 100
#define FUNCNAME_peekURL 101
#define FUNCNAME_pipeBuf 102
#define FUNCNAME_pipesh 103
#define FUNCNAME_hpgBack 104
#define FUNCNAME_prevA 105
#define FUNCNAME_prevMk 106
#define FUNCNAME_pgBack 107
#define FUNCNAME_prevBf 108
#define FUNCNAME_prevT 109
#define FUNCNAME_prevVA 110
#define FUNCNAME_movLW 111
#define FUNCNAME_svBuf 112
#define FUNCNAME_qquitfm 113
#define FUNCNAME_readsh 114
#define FUNCNAME_redoPos 115
#define FUNCNAME_rdrwSc 116
#define FUNCNAME_reMark 117
#define FUNCNAME_reinit 118
#define FUNCNAME_reload 119
#define FUNCNAME_reshape 120
#define FUNCNAME_col1R 121
#define FUNCNAME_svI 122
#define FUNCNAME_svA 123
#define FUNCNAME_srchbak 126
#define FUNCNAME_srchfor 127
#define FUNCNAME_srchnxt 128
#define FUNCNAME_srchprv 129
#define FUNCNAME_selMn 131
#define FUNCNAME_selBuf 132
#define FUNCNAME_setEnv 133
#define FUNCNAME_setOpt 134
#define FUNCNAME_sgrmouse 135
#define FUNCNAME_shiftl 137
#define FUNCNAME_shiftr 138
#define FUNCNAME_vwSrc 139
#define FUNCNAME_stopI 140
#define FUNCNAME_submitForm 141
#define FUNCNAME_tabrURL 143
#define FUNCNAME_tabURL 144
#define FUNCNAME_tabL 145
#define FUNCNAME_tabA 146
#define FUNCNAME_tabMn 147
#define FUNCNAME_tabMs 148
#define FUNCNAME_tabR 149
#define FUNCNAME_undoPos 150
#define FUNCNAME_lup1 151
#define FUNCNAME_dispVer 152
#define FUNCNAME_followI 154
#define FUNCNAME_wrapToggle 157
