#!/bin/sh
[ "$(nvram get log_wm)" -eq 1 -a "$(nvram get webmon_bkp)" -eq 1 ] && {
BKP_DIR=$(nvram get webmon_dir)
DATA=$(date +%Y%m%d_%H%M)
ACTION=$1
[ $(echo $BKP_DIR | sed -e 's/\(^.*\)\(.$\)/\2/') == "/" ] && {
echo $DIR | sed 's/.$//'
}
if [ "$ACTION" == "add" ]; then
[ "$(cru l | grep webmon | wc -l)" -eq 0 ] && {
cru a webmon_bkp "0 0 */1 * * /usr/sbin/webmon_bkp"
cru a webmon_tmp "59 * * * * /usr/sbin/webmon_bkp hourly"
}
[ -f "$BKP_DIR/webmon_recent_domains" -o -f "$BKP_DIR/webmon_recent_searches" ] && {
echo "" > /dev/null 2>&1
} || {
/usr/sbin/webmon_bkp hourly
}
elif [ "$ACTION" == "hourly" ]; then
cp /proc/webmon_recent_domains $BKP_DIR/webmon_recent_domains > /dev/null 2>&1
cp /proc/webmon_recent_searches $BKP_DIR/webmon_recent_searches > /dev/null 2>&1
else
LOGS="logger -t Webmon-Backup"
touch $BKP_DIR/$DATA > /dev/null 2>&1
[ -f "$BKP_DIR/$DATA" ] && {
rm $BKP_DIR/$DATA
cat $BKP_DIR/webmon_recent_domains | awk '{t=$1; "date -d @\""t"\" \"+%Y-%m-%d %H:%M:%S\"" | getline d;print d"\t"$2"\t"$3 }' >> $BKP_DIR/domain-$DATA.log
tar -czf $BKP_DIR/domain-$DATA.log.tar.gz $BKP_DIR/domain-$DATA.log > /dev/null 2>&1
rm $BKP_DIR/domain-$DATA.log
cat $BKP_DIR/webmon_recent_searches | awk '{t=$1; "date -d @\""t"\" \"+%Y-%m-%d %H:%M:%S\"" | getline d;print d"\t"$2"\t"$3 }' >> $BKP_DIR/search-$DATA.log
tar -czf $BKP_DIR/search-$DATA.log.tar.gz $BKP_DIR/search-$DATA.log > /dev/null 2>&1
rm $BKP_DIR/search-$DATA.log
[ -f "$BKP_DIR/domain-$DATA.log.tar.gz" -a -f "$BKP_DIR/search-$DATA.log.tar.gz" ] && {
[ "$(nvram get webmon_shrink)" -eq 1 ] && {
iptables -t filter -A monitor -p tcp -m webmon --clear_search --clear_domain
service firewall restart
$LOGS "Backup finished. Log cleared."
} || {
$LOGS "Backup finished."
}
/usr/sbin/webmon_bkp hourly
} || {
$LOGS "Failed: Something goes wrong. Backup was not created!"
}
} || {
$LOGS "Failed: Directory does not exist or is not writable!"
}
fi
}
