/*
 * Auto-generated by Frida. Please modify to match the signature of system.
 * This stub is currently auto-generated from manpages when available.
 *
 * For full API reference, see: https://frida.re/docs/javascript-api/
 *
 * Example usage:
 * $ frida-trace -i "system" ./hello-vuln
 * Instrumenting...
 * system: Loaded handler at "/home/raptor/__handlers__/libc.so.6/system.js"
 * Enter your name: Started tracing 1 function. Web UI available at http://localhost:46277/
 * canary123
 * sh: 1: modified: not found
 * ...
 *  8590 ms  system(command="echo Hello, canary123")
 *  8590 ms  system(command="modified argument!")
 *  8591 ms  system returned 0x7f00
 * Process terminated
 */

defineHandler({
  onEnter(log, args, state) {
    log(`system(command="${args[0].readUtf8String()}")`);
    args[0].writeUtf8String('modified argument!');
    log(`system(command="${args[0].readUtf8String()}")`);
  },

  onLeave(log, retval, state) {
    log(`system returned ${retval}`);
  }
});