void __fastcall sub_19F1C(int a1)
{
  const char *Var; // r0
  const char *v3; // r1
  const char *v4; // r5
  const char *v5; // r0
  bool v6; // zf
  int v7; // r5
  const char *NVRAMVar; // r0
  int v9; // r0
  int v10; // r9
  _BOOL4 v11; // r6
  const char *v12; // r0
  const char *v13; // r0
  FILE *v14; // r4
  _BOOL4 v15; // r8
  const char *v16; // r11
  const char *wanip; // r10
  const char *v18; // r0
  int v19; // r0
  int v20; // r0
  int v21; // r0
  const char *v22; // r0
  const char *v23; // r0
  int v24; // r0
  const char *v25; // r0
  const char *v26; // r0
  const char *v27; // r0
  const char *v28; // r0
  int v29; // r0
  int v30; // r7
  const char *v31; // r0
  const char *v32; // r0
  _BYTE *v33; // r0
  const char *v34; // r0
  int v35; // r0
  const char *v36; // r0
  char *v37; // r10
  int v38; // r7
  FILE *v39; // r0
  FILE *v40; // r7
  const char *v41; // r0
  const char *v42; // r0
  const char *v43; // r0
  const char *v44; // r0
  const char *v45; // r0
  const char *v46; // r0
  char *v47; // r6
  const char *v48; // r0
  const char *v49; // r0
  const char *v50; // r0
  int v51; // [sp+Ch] [bp-2164h]
  _BYTE v52[8172]; // [sp+14h] [bp-215Ch] BYREF
  char v53[256]; // [sp+2014h] [bp-15Ch] BYREF
  char *v54; // [sp+2114h] [bp-5Ch] BYREF
  const char *v55; // [sp+2118h] [bp-58h]
  const char *v56; // [sp+211Ch] [bp-54h]
  const char *v57; // [sp+2120h] [bp-50h]
  const char *v58; // [sp+2124h] [bp-4Ch]
  char *v59; // [sp+2128h] [bp-48h]
  int v60; // [sp+212Ch] [bp-44h]
  struct in_addr v61; // [sp+2130h] [bp-40h] BYREF
  struct in_addr v62; // [sp+2134h] [bp-3Ch] BYREF
  char *v63; // [sp+2138h] [bp-38h] BYREF
  const char *v64; // [sp+213Ch] [bp-34h]
  const char *v65; // [sp+2140h] [bp-30h]
  int v66; // [sp+2144h] [bp-2Ch]

  Var = (const char *)WebsGetVar("_server");
  v3 = &s;
  if ( Var )
    v3 = Var;
  strlcpy((int)v53, (int)v3, 256);
  v4 = (const char *)sub_E6BC(v53);
  strlcpy((int)v53, a1, 256);
  v5 = (const char *)sub_E6BC(v53);
  v6 = v4 == 0;
  if ( v4 )
    v6 = v5 == 0;
  if ( v6 )
  {
    syslog(4, "No server '%s' for /%s", v4, v5);
    return;
  }
  v7 = atoi(v4);
  NVRAMVar = (const char *)getNVRAMVar();
  v9 = atoi(NVRAMVar);
  v10 = v9;
  if ( v9 )
  {
    v12 = (const char *)getNVRAMVar();
    v11 = atoi(v12) != 0;
  }
  else
  {
    v11 = 0;
  }
  v13 = (const char *)WebsGetVar("_userid");
  if ( !v13 )
    v13 = "0";
  v51 = atoi(v13);
  v54 = "rm";
  v55 = "-Rf";
  v56 = "/tmp/ovpnclientconfig";
  v57 = 0;
  eval(&v54, 0, 0, 0);
  v54 = "mkdir";
  v55 = "-m";
  v56 = "0777";
  v57 = "-p";
  v58 = "/tmp/ovpnclientconfig";
  v59 = 0;
  eval(&v54, 0, 0, 0);
  v14 = fopen("/tmp/ovpnclientconfig/connection.ovpn", "w");
  if ( !v14 )
  {
    perror("/tmp/ovpnclientconfig/connection.ovpn");
    return;
  }
  memset(v53, 0, sizeof(v53));
  snprintf(v53, 0x100u, "vpn_server%d_crypt", v7);
  v15 = is_value_in_nvram_2((int)v53, "tls");
  v16 = sub_19758((int)"os_version");
  wanip = (const char *)get_wanip("wan");
  v18 = (const char *)getNVRAMVar();
  v19 = atoi(v18);
  fprintf(
    v14,
    "# Config generated by FreshTomato %s, requires OpenVPN 2.4.0 or newer\n\nremote %s %d\n",
    v16,
    wanip,
    v19);
  v20 = getNVRAMVar();
  strlcpy((int)v53, v20, 256);
  sub_CEE0(v53, "-server", "-client");
  fprintf(v14, "proto %s\n", v53);
  v21 = getNVRAMVar();
  strlcpy((int)v53, v21, 256);
  if ( strcmp(v53, "-1") )
  {
    if ( !strcmp(v53, "lz4") || !strcmp(v53, "lz4-v2") )
    {
      fprintf(v14, "compress %s\n", v53);
      goto LABEL_26;
    }
    if ( !strcmp(v53, "yes") )
    {
      v22 = "compress lzo\n";
    }
    else if ( !strcmp(v53, "adaptive") )
    {
      v22 = "comp-lzo adaptive\n";
    }
    else
    {
      if ( strcmp(v53, "no") )
        goto LABEL_26;
      v22 = "compress\n";
    }
    fputs(v22, v14);
  }
LABEL_26:
  v23 = (const char *)getNVRAMVar();
  fprintf(v14, "dev %s\n", v23);
  v24 = getNVRAMVar();
  strlcpy((int)v53, v24, 256);
  if ( v15 )
  {
    if ( v53[0] )
      fprintf(v14, "ncp-ciphers %s\n", v53);
  }
  else
  {
    memset(v53, 0, sizeof(v53));
    snprintf(v53, 0x100u, "vpn_server%d_cipher", v7);
    if ( !nvram_contains_word(v53, "default") )
    {
      v25 = sub_19758((int)v53);
      fprintf(v14, "cipher %s\n", v25);
    }
  }
  memset(v53, 0, sizeof(v53));
  snprintf(v53, 0x100u, "vpn_server%d_digest", v7);
  if ( !nvram_contains_word(v53, "default") )
  {
    v26 = sub_19758((int)v53);
    fprintf(v14, "auth %s\n", v26);
  }
  if ( v15 )
  {
    v27 = (const char *)getNVRAMVar();
    fprintf(v14, "client\nremote-cert-tls server\n; ca ca.pem\n<ca>\n%s\n</ca>\n\n", v27);
    v28 = (const char *)getNVRAMVar();
    sub_19774("/tmp/ovpnclientconfig/ca.pem", v28);
    memset(v53, 0, sizeof(v53));
    snprintf(v53, 0x100u, "vpn_server%d_hmac", v7);
    v29 = nvram_get_int(v53);
    v30 = v29;
    if ( v29 < 0 )
    {
LABEL_51:
      if ( v10 )
      {
        fputs("auth-user-pass auth.txt\n", v14);
        v36 = (const char *)getNVRAMVar();
        v37 = strdup(v36);
        v63 = v37;
        if ( v37 )
        {
          v38 = 0;
          while ( v63 && strsep(&v63, ">") )
          {
            v64 = 0;
            v65 = 0;
            v66 = 0;
            ++v38;
            if ( vstrsep() > 2 && *v65 && *v64 && v38 == v51 )
            {
              v39 = fopen("/tmp/ovpnclientconfig/auth.txt", "w");
              v40 = v39;
              if ( v39 )
              {
                fprintf(v39, "%s\n%s\n", v65, v64);
                fclose(v40);
              }
              break;
            }
          }
          free(v37);
        }
      }
      if ( !v11 )
      {
        sub_197B8(v7);
        sub_19994("client", v51);
        v54 = "cp";
        v55 = "/tmp/openssl/client.crt";
        v56 = "/tmp/ovpnclientconfig";
        v57 = 0;
        eval(&v54, 0, 0, 0);
        v54 = "cp";
        v55 = "/tmp/openssl/client.key";
        v56 = "/tmp/ovpnclientconfig";
        v57 = 0;
        eval(&v54, 0, 0, 0);
        v41 = sub_19BB0((int)"/tmp/ovpnclientconfig/client.crt", v52, 0x2000);
        fprintf(v14, "; cert client.crt\n<cert>\n%s\n</cert>\n\n", v41);
        v42 = sub_19BB0((int)"/tmp/ovpnclientconfig/client.key", v52, 0x2000);
        fprintf(v14, "; key client.key\n<key>\n%s\n</key>\n\n", v42);
      }
      goto LABEL_69;
    }
    if ( v29 == 3 )
    {
      v31 = "; tls-crypt static.key";
    }
    else if ( v29 == 4 )
    {
      v31 = "; tls-crypt-v2 static.key";
    }
    else
    {
      fputs("; tls-auth static.key", v14);
      if ( v30 )
      {
        if ( v30 == 1 )
        {
          fputs(" 0\n", v14);
          v31 = "key-direction 0\n";
        }
        else
        {
          if ( v30 != 2 )
            goto LABEL_46;
          v31 = "key-direction bidirectional\n";
        }
      }
      else
      {
        fputs(" 1\n", v14);
        v31 = "key-direction 1\n";
      }
    }
    fputs(v31, v14);
LABEL_46:
    fputc(10, v14);
    if ( v30 == 4 )
    {
      v32 = (const char *)getNVRAMVar();
      sub_19774("/tmp/ovpnclientconfig/static-server.key", v32);
      system(
        "openvpn --tls-crypt-v2 /tmp/ovpnclientconfig/static-server.key --genkey tls-crypt-v2-client /tmp/ovpnclientconfi"
        "g/static.key >/dev/null 2>&1");
      v54 = "rm";
      v55 = "/tmp/ovpnclientconfig/static-server.key";
      v56 = 0;
      eval(&v54, 0, 0, 0);
      v33 = sub_19BB0((int)"/tmp/ovpnclientconfig/static.key", v52, 0x2000);
      fprintf(v14, "<tls-crypt-v2>\n%s\n</tls-crypt-v2>\n\n", v33);
    }
    else
    {
      v34 = (const char *)getNVRAMVar();
      sub_19774("/tmp/ovpnclientconfig/static.key", v34);
      v35 = getNVRAMVar();
      if ( v30 == 3 )
        fprintf(v14, "<tls-crypt>\n%s\n</tls-crypt>\n\n", v35);
      else
        fprintf(v14, "<tls-auth>\n%s\n</tls-auth>\n\n", v35);
    }
    goto LABEL_51;
  }
  fputs("mode p2p\n", v14);
  memset(v53, 0, sizeof(v53));
  snprintf(v53, 0x100u, "vpn_server%d_if", v7);
  nvram_contains_word(v53, "tap");
  v43 = (const char *)getNVRAMVar();
  fprintf(v14, "ifconfig %s ", v43);
  v44 = (const char *)getNVRAMVar();
  fprintf(v14, "%s\n", v44);
  v45 = sub_19758((int)"lan_ipaddr");
  if ( inet_aton(v45, &v62) )
  {
    v46 = sub_19758((int)"lan_netmask");
    if ( inet_aton(v46, &v61) )
    {
      v47 = inet_ntoa((struct in_addr)(v61.s_addr & v62.s_addr));
      v48 = sub_19758((int)"lan_netmask");
      fprintf(v14, "route %s %s\n", v47, v48);
    }
  }
  v49 = (const char *)getNVRAMVar();
  fprintf(v14, "; secret static.key\n<secret>\n%s\n</secret>\n\n", v49);
  v50 = (const char *)getNVRAMVar();
  sub_19774("/tmp/ovpnclientconfig/static.key", v50);
LABEL_69:
  fputs(
    "keepalive 15 60\nresolv-retry infinite\nnobind\nfloat\nverb 3\nstatus status\n; log /var/log/openvpn.log\n",
    v14);
  fclose(v14);
  v54 = "tar";
  v55 = "-cf";
  v56 = "/tmp/ovpnclientconfig.tar";
  v57 = "-C";
  v58 = "/tmp/ovpnclientconfig";
  v59 = ".";
  v60 = 0;
  eval(&v54, 0, 0, 0);
  sub_C3F0("/tmp/ovpnclientconfig.tar");
}
